apiVersion: v1
kind: Secret
metadata:
  name: argocd-test
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/tdinucci/argocd-test.git