apiVersion: v1
kind: ConfigMap
metadata:
  name: service-d-config
data:
  nginx.conf: '
events {
}
http {
   server {
       listen 80;
       location / {
           return 200 "Hello from service-d";
       }
   }
}
'
